apiVersion: v1
kind: Service
metadata:
  name: payment-execution-service
  labels:
    app: payment-execution-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 3000
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: payment-execution-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment-execution-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-execution-app
    spec:
      containers:
      - name: payment-execution-app
        image: payment-execution
        # for local development against minikube registry
        #imagePullPolicy: Never
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /opt/service-bind
          name: service-bind-volume
      volumes:
      - name: service-bind-volume
        secret:
          defaultMode: 420
          secretName:
